// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Entities;

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0baa5e42-08da-41ed-b557-1067bbe20b1c"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("e03a4ca4-f32e-4fc6-af5c-8b879a2f3946"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("033fce2e-8409-402d-8914-adde5c08df7e"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("8938fe01-9a53-4fb1-9402-4cae748bc75f"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("7b77e519-5053-4076-8e26-ada51a7f2f29"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("8938fe01-9a53-4fb1-9402-4cae748bc75f"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("backend.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e03a4ca4-f32e-4fc6-af5c-8b879a2f3946"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("8938fe01-9a53-4fb1-9402-4cae748bc75f"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("backend.Entities.Account", b =>
                {
                    b.HasOne("backend.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
